site_name: DBML Plugin Demo
site_description: Демонстрация плагина MkDocs для рендеринга DBML

theme:
  name: readthedocs

plugins:
  - search
  - dbml:
      theme: black
      show_indexes: true
      show_notes: true

nav:
  - Главная: index.md
  - Интерактивность: interactive.md
  - Примеры: examples.md
  - Продвинутые: advanced.md
  - Темы: themes.md
