site_name: DBML Plugin Demo
site_description: MkDocs plugin for rendering DBML as interactive ERD diagrams

theme:
  name: readthedocs

plugins:
  - search
  - dbml:
      theme: black
      show_indexes: true
      show_notes: true

nav:
  - Home: index.md
  - Interactivity: interactive.md
  - Examples: examples.md
  - Advanced: advanced.md
  - Themes: themes.md
